### ISSUE TITLE
Provide a consistent and language-agnostic documentation

### ISSUE THREAD

**Issue by yanishoss** [ory/hydra-login-consent-node#13]
# Provide a consistent and language-agnostic documentation
## Issue
The login-consent flow in the Hydra's documentation is very unclear and the only reference for it is this implementation.
## Proposal
Instead of giving a bare implementation as a documentation, please include in the Hydra's documentation a language-agnostic documention of the login-consent flow.
## Example
Let's say this is the documention's part about the login-consent flow:
1. Hydra make a request to your login endpoint with:
    * Method: GET
    * Query parameters: challenge_id, subject, ...
1. Your endpoint must make a request to /oauth/requests with:
    * Method: POST
    * Content-Type: application/json
    * Query parameters: challenge_id, ...
1. ...
## Aside
I came up with this issue trying to figure out how to write a login-consent flow using an SPA instead of a server-side rendered webapp.
## Solution
Please comment this issue with your language-agnostic login-consent flow documentation to help the Hydra's team to do it more quickly.

**Comment by aeneasr** [comment]
Hey, this is great feedback. Would you mind helping in improving the documentation around that? I'm also curious to know if [this](https://www.ory.sh/docs/hydra/oauth2#implementing-a-login-consent-provider) is too language-dependent?

Feel free to create an issue in the [docs](https://github.com/ory/docs/issues) or even a PR to improve this!

**Comment by yanishoss** [comment]
Actually, it is good but, hey, there can’t be sentences like « such as... »
in a documentation, we need something really precise with a table like
you’ve done with the API reference of Hydra

**Comment by aeneasr** [comment]
Happy to work together to improve this - would you be open to create a PR in the docs with ideas for improvement and we work together towards better docs? This will probably also help you better understand how this flow works :)

**Comment by yanishoss** [comment]
I've basically gone through the whole code for hints about the
login-consent flow so I'm good with it, gonna write a PR in the docs ASAP

Le jeu. 28 févr. 2019 à 10:14, hackerman <notifications@github.com> a
écrit :

**Comment by aeneasr** [comment]
Awesome! :)
