### ISSUE TITLE
Using Latest Hydra we are getting error

### ISSUE THREAD

**Issue by mvsiva4u** [ory/hydra-login-consent-node#23]
We are getting below are while running the node server and opening the page in browser.

at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by aeneasr** [comment]
Thank you for creating an issue in this repository. Unfortunately, your issue does not comply with community guidelines by not using one of the provided issue templates. Those templates help us better understand your issue and reduce latency as well as communication overhead. Please update your issue in accordance with the [issue template](../tree/master/.github/ISSUE_TEMPLATE) that fits best or this issue will be auto-closed in a 3 days.

**Comment by mvsiva4u** [comment]
docker run --link login-consent-hydra:hydra oryd/hydra:v1.0.0 clients create \
>     --endpoint http://hydra:4445 \
>     --id test-client \
>     --response-types code,id_token \
>     --grant-types refresh_token,authorization_code \
>     --scope openid,offline \
>     --callbacks http://127.0.0.1:4446/callback

After updating the hydra v1.0.0 running through Docker and calling the above command. we are getting the below message.
Config file not found because "Config File ".hydra" Not Found in "[/]""

**Comment by aeneasr** [comment]
Please read the [documentation](https://www.ory.sh/docs) and [upgrade guides](https://github.com/ory/hydra/blob/master/UPGRADE.md).
