### ISSUE TITLE
Cannot set MOCK_TLS_TERMINATION

### ISSUE THREAD

**Issue by msanguineti** [ory/hydra-login-consent-node#69]
**Describe the bug**

Setting the env variable `MOCK_TLS_TERMINATION` results in a crash:

`TypeError: Cannot set property 'X-Forwarded-Proto' of undefined`

**To Reproduce**

1: set the env variable `MOCK_TLS_TERMINATION` to true
2: run the application

**Expected behavior**

The application should not crash and the header `X-Forwarded-Proto` should be set.

**Environment**

- Version: v1.9.0
- Environment: Debian 10

**Comment by aeneasr** [comment]
Yes that's definitely a bug! If you have a fix feel free to contribute!
